src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use App\Traits\CustomerData;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;
use Symfony\Component\Validator\Constraints\DateTime;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
class Order
{
    use CustomerData;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne]
    #[JoinColumn(name: 'user_id', referencedColumnName: 'id')]
    private ?User $user = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Car $car = null;

    #[ORM\Column(length: 255)]
    private ?string $methodOfPayment = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $startDate = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $endDate = null;

    #[ORM\OneToOne(mappedBy: 'order', targetEntity: Address::class)]
    #[JoinColumn(name: 'address_id', referencedColumnName: 'id')]
    private ?Address $address = null;
    #[ORM\OneToOne(mappedBy: 'order', targetEntity: DeliveryAddress::class)]
    #[JoinColumn(name: 'delivery_address_id', referencedColumnName: 'id')]
    private ?DeliveryAddress $deliveryAddress = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 25)]
    private ?string $status = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $lastEdit = null;

    #[ORM\Column(type: "boolean")]
    private bool $carSeat = false;

    #[ORM\Column(type: "boolean")]
    private bool $dogCage = false;

    #[ORM\Column]
    private ?int $childSeat = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCar(): ?Car
    {
        return $this->car;
    }

    public function setCar(?Car $car): self
    {
        $this->car = $car;

        return $this;
    }

    public function getMethodOfPayment(): ?string
    {
        return $this->methodOfPayment;
    }

    public function setMethodOfPayment(string $methodOfPayment): self
    {
        $this->methodOfPayment = $methodOfPayment;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getDeliveryAddress(): ?DeliveryAddress
    {
        return $this->deliveryAddress;
    }

    public function setDeliveryAddress(DeliveryAddress $deliveryAddress): self
    {
        $this->deliveryAddress = $deliveryAddress;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTotalTime(): \DateInterval
    {
        return date_diff($this->startDate, $this->endDate);
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getLastEdit(): ?\DateTimeInterface
    {
        return $this->lastEdit;
    }

    public function setLastEdit(\DateTimeInterface $lastEdit): self
    {
        $this->lastEdit = $lastEdit;

        return $this;
    }

    public function hasCarSeat(): bool
    {
        return $this->carSeat;
    }

    public function setCarSeat(bool $carSeat): void
    {
        $this->carSeat = $carSeat;
    }

    public function hasDogCage(): bool
    {
        return $this->dogCage;
    }

    public function setDogCage(bool $dogCage): void
    {
        $this->dogCage = $dogCage;
    }

    /**
     * @return Address|null
     */
    public function getAddress(): ?Address
    {
        return $this->address;
    }

    /**
     * @param Address|null $address
     */
    public function setAddress(?Address $address): void
    {
        $this->address = $address;
    }

    public function isCancelable(): bool
    {
        $now = new \DateTime();
        $startDate24HoursBefore = $this->getStartDate()->sub(new \DateInterval('P1D'));
        return $now < $startDate24HoursBefore && $this->getStatus() != 'Cancelled';
    }


    public function getChildSeat(): ?int
    {
        return $this->childSeat;
    }

    public function setChildSeat(int $childSeat): self
    {
        $this->childSeat = $childSeat;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use App\Traits\CustomerData;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints\Cascade;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'Ein Benutzerkonto mit dieser Emailadresse existiert bereits.')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    use CustomerData;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $preferredMethodOfPayment = null;

    #[ORM\OneToOne(mappedBy: 'user', targetEntity: Address::class, cascade: ['remove'])]
    #[JoinColumn(name: 'address_id', referencedColumnName: 'id', onDelete: 'SET NULL')]
    private ?Address $address;

    public function __construct()
    {
        $this->address = new Address();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string)$this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPreferredMethodOfPayment(): ?string
    {
        return $this->preferredMethodOfPayment;
    }

    public function setPreferredMethodOfPayment(string $preferredMethodOfPayment): self
    {
        $this->preferredMethodOfPayment = $preferredMethodOfPayment;

        return $this;
    }

    public function getAddress(): ?Address
    {
        return $this->address;
    }

    public function setAddress(?Address $address): ?self
    {
        $this->address = $address;

        return $this;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Address;
use App\Entity\Order;
use App\Entity\User;
use App\Enum\FlashMessages;
use App\Form\AddressFormType;
use App\Form\ChangePasswordFormType;
use App\Form\EditUserFormType;
use App\Form\RegistrationFormType;
use App\Service\OrderMailer;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Contracts\Translation\TranslatorInterface;

use function Deployer\test;

class UserController extends AbstractController
{
    #[Route('/{_locale}/registrierung', name: 'register')]
    #[Route('/{_locale}/create-account', name: 'register_en')]
    public function register(
        MailerInterface $mailer,
        Request $request,
        UserPasswordHasherInterface $userPasswordHasher,
        EntityManagerInterface $entityManager,
        TranslatorInterface $translator
    ): Response {
        $user = new User();
        $address = new Address();
        $form = $this->createForm(RegistrationFormType::class, $user);
        $addressForm = $this->createForm(AddressFormType::class, $address);
        $form->handleRequest($request);
        $addressForm->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid() && $addressForm->isValid()) {
            $address->setUser($user);
            $user->setAddress($address);
            $user->setPassword(
                $userPasswordHasher->hashPassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );
            $entityManager->persist($address);
            $entityManager->persist($user);
            $entityManager->flush();
            $this->addFlash('success', $translator->trans(FlashMessages::SUCCESS_REGISTER->toString()));
            $email = (new TemplatedEmail())
                ->text($translator->trans('Register.success'))
                ->to($user->getEmail())
                ->subject($translator->trans('Register.success'))
                ->htmlTemplate('emails/email_register_confirmation.html.twig')
                ->context([
                    'user' => $user
                ]);
            $mailer->send($email);
            return $this->redirectToRoute('login');
        }
        return $this->render('user/register.html.twig', [
            'form' => $form,
            'addressForm' => $addressForm,
            'title' => 'Register',
        ]);
    }

    #[Route('/{_locale}/anmelden', name: 'login')]
    #[Route('/{_locale}/login', name: 'login_en')]
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        $error = $authenticationUtils->getLastAuthenticationError();
        $lastUsername = $authenticationUtils->getLastUsername();
        return $this->render('user/login.html.twig', [
            'last_username' => $lastUsername,
            'error' => $error,
            'title' => '',
        ]);
    }

    #[Route('/{_locale}/aktualisieren', name: 'user_edit')]
    #[Route('/{_locale}/edit-profile', name: 'user_edit_en')]
    public function edit(
        EntityManagerInterface $entityManager,
        Request $request,
        TranslatorInterface $translator
    ): Response {
        $user = $this->getUser();
        $address = $user->getAddress();
        if ($address == null) {
            $address = new Address();
            $user->setAddress($address);
            $address->setUser($user);
        }
        $form = $this->createForm(EditUserFormType::class, $user);
        $addressForm = $this->createForm(AddressFormType::class, $address);
        $addressForm->handleRequest($request);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid() && $addressForm->isValid()) {
            $entityManager->persist($address);
            $entityManager->flush();
            $this->addFlash('success', $translator->trans(FlashMessages::SUCCESS_EDIT->toString()));
            return $this->redirectToRoute('homepage');
        }
        return $this->render('user/edit.html.twig', [
            'form' => $form,
            'addressForm' => $addressForm,
            'title' => 'Edit.profile',
        ]);
    }

    #[Route('/{_locale}/logout', name: 'user_logout', methods: ['GET'])]
    public function logout(TranslatorInterface $translator)
    {
    }

    #[Route('/{_locale}/logout_message', name: 'logout_message')]
    public function logoutMessage(TranslatorInterface $translator)
    {
        $this->addFlash('success', $translator->trans(FlashMessages::SUCCESS_LOGOUT->toString()));
        return $this->redirectToRoute('homepage');
    }

    #[Route('/{_locale}/delete-account', name: 'delete_account')]
    public function deleteAccount(
        Request $request,
        EntityManagerInterface $entityManager,
        TranslatorInterface $translator,
        Security $security
    ): Response {
        /** @var User $user */
        $user = $entityManager->getRepository(User::class)->findOneBy(['id' => $this->getUser()]);
        $isThereAnyActuallyBooking = $entityManager->getRepository(Order::class)->isThereAnyActuallyBooking($user);
        $dummyUser = $entityManager->getRepository(User::class)->getDummyUser();
        $orders = $entityManager->getRepository(Order::class)->findBy(['user' => $user]);
        $address = $dummyUser->getAddress();
        $address->setUser($dummyUser);
        $entityManager->persist($address);
        $entityManager->persist($dummyUser);

        if (!$isThereAnyActuallyBooking) {
            foreach ($orders as $order) {
                /** @var Order $order */
                $order->setUser($dummyUser);
                $entityManager->flush();
            }
            $security->logout(validateCsrfToken: false);
            $entityManager->remove($user);
            $entityManager->flush();
            $this->addFlash('success', $translator->trans(FlashMessages::SUCCESS_DELETING_ACCOUNT->toString()));
            return $this->redirectToRoute('login');
        }
        $this->addFlash('danger', $translator->trans(FlashMessages::ERROR_DELETING_ACCOUNT->toString()));
        return $this->redirectToRoute('user_edit');
    }

    #[Route('/{_locale}/changePassword', name: 'change_password')]
    public function changePassword(
        Request $request,
        EntityManagerInterface $entityManager,
        TranslatorInterface $translator,
        UserPasswordHasherInterface $hasher
    ): Response {
        $form = $this->createForm(ChangePasswordFormType::class);
        $user = $this->getUser();

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $oldpassword = $form->get('oldPassword')->getData();
            if ($oldpassword && $hasher->isPasswordValid($user, $oldpassword)) {
                $newPassword = $form->get('newPassword')->getData();
                if ($newPassword) {
                    $password = $hasher->hashPassword($user, $newPassword);
                    $user->setPassword($password);
                    $entityManager->flush();
                    $this->addFlash('success', $translator->trans(FlashMessages::SUCCESS_EDIT->toString()));
                    return $this->redirectToRoute('homepage');
                }
            } else {
                $this->addFlash("warning", $translator->trans("Form.password.wrongPassword"));
            }
        }
        return $this->render('user/change_password.html.twig', ['title' => 'Password.change', 'form' => $form]);
    }

    #[Route('/{_locale}/rentalAgreement', name: 'rental_agreement')]
    public function rentalAgreement(
        Request $request,
        TranslatorInterface $translator,
        EntityManagerInterface $entityManager,
        OrderMailer $orderMailer,
    ): Response {
        $rentals = $entityManager->getRepository(Order::class)->findBy(['user' => $this->getUser()]);

        if ($request->get('id')) {
            $order = $entityManager->getRepository(Order::class)->find($request->get('id'));
            $order->setStatus('Cancelled');
            $entityManager->flush();
            $orderMailer->sendCanceledRentalAgreementMail($order);
            $this->addFlash('success', $translator->trans(FlashMessages::SUCCESS_DELETING_RENTAL->toString()));
        }
        return $this->render(
            'user/rental_agreement.html.twig',
            ['title' => 'Cancel', 'rentals' => $rentals]
        );
    }
}

templates/user/change_password.html.twig
{% extends 'base.html.twig' %}
{% block searchbar %}{% endblock %}
{% block body %}
    <div class="container">
        {{ form(form) }}
    </div>
{% endblock %}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}
        {% block searchbar %}{% endblock %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="row">
                    {{ form_start(form) }}
                    <div class="my-custom-class-for-errors">
                        {{ form_errors(form) }}
                    </div>
                    <div class="row">
                        <div class="col">
                            {{ form_row(form.formOfAddress) }}
                        </div>
                        <div class="col">
                            {{ form_row(form.firstName) }}
                        </div>
                        <div class="col" id="some-custom-id">
                            {{ form_row(form.lastName) }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            {{ form_row(form.email) }}
                        </div>
                        <div class="col">
                            {{ form_row(form.phoneNumber) }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 col-md-6 col-lg-5">
                            {{ form_row(addressForm.country) }}
                        </div>
                        <div class="col-12 col-md-6 col-lg-2">
                            {{ form_row(addressForm.zipCode) }}
                        </div>
                        <div class="col-12 col-md-6 col-lg-5">
                            {{ form_row(addressForm.city) }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 col-md-6 col-lg-5">
                            {{ form_row(addressForm.street) }}
                        </div>
                        <div class="col-12 col-md-6 col-lg-2">
                            {{ form_row(addressForm.houseNumber) }}
                        </div>
                        <div class="col-12 col-md-6 col-lg-5">
                            {{ form_row(addressForm.comments) }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            {{ form_row(form.preferredMethodOfPayment) }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            {{ form_row(form.submit) }}
                        </div>
                        <div class="col">
                            <button name="" value="" type="submit" onclick="return confirm('{{ 'Message.deleting.account' | trans }}')" formmethod="post" formaction="{{ path('delete_account') }}" class="btn btn-danger float-center float-md-end">{{ 'Delete.account' | trans}}</button>
                        </div>
                    </div>

                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/login.html.twig
{% extends 'base.html.twig' %}
{% block title %}Mobilmacher - Anmelden{% endblock %}
{% block title2 %}{% endblock %}
{% block searchbar %}{% endblock %}
{% block body %}
    <div class="container">
        {% if error %}
            <div class="alert alert-warning">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
        {% endif %}
        <div class="row">
            <main class="col-lg-6 mx-auto">
                <form action="{{ path('login') }}" method="post">
                    <h1 class="mb-5 fs-2 fw-normal text-secondary">{{ 'Link.login' | trans }}</h1>
                    <div class="form-floating mb-3">
                        <input type="email" class="form-control" id="floatingInput" value="{{ last_username }}"
                               name="_username"
                               placeholder="name@example.com">
                        <label for="floatingInput">{{ 'Email' | trans}}</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" class="form-control" name="_password" id="floatingPassword"
                               placeholder="Password">
                        <label for="floatingPassword">{{ 'Password' | trans }}</label>
                    </div>

                    <input type="hidden" name="_target_path" value="/{{ app.request.locale }}">
                    <button class="w-100 btn btn-lg btn-primary" type="submit">{{ 'Link.login' | trans }}</button>

                    <a href="{{ path('app_forgot_password_request') }}">Passwort vergessen</a>

                </form>
            </main>
        </div>
    </div>

{% endblock %}

templates/user/register.html.twig
{% extends 'base.html.twig' %}
{% block title %}Mobilmacher - {{ 'Register' | trans }}{% endblock %}
{% block searchbar %}{% endblock %}
{% block body %}
    <div class="container">
        <div class="row">
                {{ form_start(form) }}
                <div class="my-custom-class-for-errors">
                    {{ form_errors(form) }}
                </div>
                <div class="row">
                    <div class="col-12 col-lg-4">
                        {{ form_row(form.formOfAddress) }}
                    </div>
                    <div class="col-12 col-md-6 col-lg-4">
                        {{ form_row(form.firstName) }}
                    </div>
                    <div class="col-12 col-md-6 col-lg-4" id="some-custom-id">
                        {{ form_row(form.lastName) }}
                    </div>
                </div>
            <div class="row">
                <div class="col-12 col-md-6">
                    {{ form_row(form.email) }}
                </div>
                <div class="col-12 col-md-6">
                    {{ form_row(form.phoneNumber) }}
                </div>
            </div>
            <div class="row">
                <div class="col-12 col-md-6 col-lg-5">
                    {{ form_row(addressForm.country) }}
                </div>
                <div class="col-12 col-md-6 col-lg-2">
                    {{ form_row(addressForm.zipCode) }}
                </div>
                <div class="col-12 col-md-6 col-lg-5">
                    {{ form_row(addressForm.city) }}
                </div>
            </div>
            <div class="row">
                <div class="col-12 col-md-6 col-lg-5">
                    {{ form_row(addressForm.street) }}
                </div>
                <div class="col-12 col-md-6 col-lg-2">
                    {{ form_row(addressForm.houseNumber) }}
                </div>
                <div class="col-12 col-md-6 col-lg-5">
                    {{ form_row(addressForm.comments) }}
                </div>
            </div>
            <div class="row">
                <div class="col">
                    {{ form_row(form.preferredMethodOfPayment) }}
                </div>
            </div>
                {{ form_end(form) }}
        </div>
    </div>

{% endblock %}

templates/user/rental_agreement.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col pt-3">
                <table class="table table-striped" id="cancelList">
                    <thead>
                    <tr>
                        <th>{{ 'Fullname' | trans }}</th>
                        <th>{{ 'Starttime' | trans }}</th>
                        <th>{{ 'Endtime' | trans }}</th>
                        <th>{{ 'Car' | trans }}</th>
                        <th>{{ 'Extras' | trans }}</th>
                        <th data-sortable="false">{{ 'Cancel' | trans }}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order in rentals %}
                    <tr>
                        <td>{{ order.getFirstname }} {{ order.getLastname }}</td>
                        <td data-sort="{{ order.getStartdate| date('Y-m-dTH:i') }}">{{ order.getStartdate | date("d.m.Y H:i") }} </td>
                        <td data-sort="{{ order.getEnddate| date('Y-m-dTH:i') }}">{{ order.getEnddate | date("d.m.Y H:i") }} </td>
                        <td>{{ order.getCar().getName }} </td>
                        <td>{% if order.hasCarSeat %}{{ 'Form.car.seat' | trans }}{% endif %}{% if order.hasCarSeat and order.hasDogCage %}, {% endif %}{% if order.hasDogCage %}{{ 'Form.dog.cage'| trans }} {% endif %}</td>
                        <td>
                            <form method="post" action="{{ path('rental_agreement') }}">
                                <button type="submit"
                                        name="id" {% if order.cancelable %} {% else %} disabled {% endif %}
                                        onclick="return confirm('{{ 'Success.deleting.rental.warning' | trans }}')"
                                        value="{{ order.id }}" class="btn btn-danger btn-sm">{{ 'Cancel' | trans }}</button>
                            </form>
                        </td>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {% if app.request.locale == 'de' %}
        <script>

            $(document).ready(function () {
                $('#cancelList').DataTable(
                    {
                        "lengthMenu": [5, 10, 20, 50, 100],
                        order: [[
                            2, 'asc'
                        ]],
                        language: {
                            url: '//cdn.datatables.net/plug-ins/1.13.4/i18n/de-DE.json',
                        },
                        "searching": false,
                        "info": false,
                    }
                );
            });
        </script>
    {% else %}
        <script>
            $(document).ready(function () {
                $('#cancelList').DataTable(
                    {
                        "lengthMenu": [5, 10, 20, 50, 100],
                        order: [[
                            2, 'asc'
                        ]],
                        "searching": false,
                        "info": false,
                    }
                );
            });
        </script>
    {% endif %}
{% endblock %}